### ISSUE TITLE
Duplicate entries in project picker

### ISSUE THREAD

**Issue by ghillb** [nvim-telescope/telescope-project.nvim#53] opened 2021-07-17 09:15 UTC
Hi, 

I'm facing the following  bug with the project picker:

## Issue
Projects are duplicated in the project picker, once with double slash after `code` directory (see screenshot). This happens to all projects within the `code` directory

**Folder structure:**
```
/home/g/                       (git dir)
     - some_project 1          (git dir)
     - code/                   (no git dir)
          - some_project 2     (git dir)
          - some_project 3     (git dir)
 ```
       
## Screenshot
![telescope projects](https://user-images.githubusercontent.com/35503959/126032155-274b1854-df16-43ae-8594-8a7f85faf78a.png)

## Setup
- nvim 0.5 stable release
- Ubuntu 21.04

## Minimal vimrc:
```
silent! packadd minpac
call minpac#init({'verbose': 3})
call minpac#add('nvim-lua/popup.nvim')
call minpac#add('nvim-lua/plenary.nvim')
call minpac#add('nvim-telescope/telescope.nvim')
call minpac#add('nvim-telescope/telescope-project.nvim')

nn <esc><esc> <cmd>Telescope project display_type=full<cr>

lua <<EOF
local ok, telescope = pcall(require, 'telescope')
if not ok then
  return
end
 
local actions = require('telescope.actions')
 
local config = {
  defaults = {
    layout_config = {
      horizontal = { 
        preview_width = 0.6
      },
      center = { 
      },
      vertical = {
      }
    },
    mappings = {
      i = {
        ["<c-s>"] = actions.file_split,
        ["<esc>"] = actions.close,
      },
      n = {
        ["<c-s>"] = actions.file_split,
      }
    }
  },
  pickers = {
    buffers = {
      sort_lastused = true,
      theme = "dropdown",
      previewer = false,
      mappings = {
        i = {
          ["<c-d>"] = actions.delete_buffer,
        },
        n = {
          ["<c-d>"] = actions.delete_buffer,
        }
      }
    }
  },
  extensions = {
    project = {
      base_dirs = {
        {'~/code', max_depth = 1}
      }
    }
  }
}
 
telescope.setup(config)
telescope.load_extension('project')
EOF
```

**Comment by claidler** [comment] 2021-07-17 21:03
@ghillb I'll have to have a look into this one. In the meantime, could you try clearing your telescope-project.txt file, which should be located at ~/.local/share/nvim (if I remember correctly)?

Then open neovim again and see if the issue is still occurring

**Comment by ghillb** [comment] 2021-07-18 08:27
I cleared `~/.local/share/nvim/telescope-projects.txt`, as you suggested, and the issue is gone, thank you!

**Comment by claidler** [comment] 2021-07-18 14:53
No probs @ghillb I'll close this one for now as it's resolved for you, but will come back and try and figure out what happened in the first place!

**Closed** 2021-07-18 14:53 UTC
