### ISSUE TITLE
Stay in prompt after selecting project

### ISSUE THREAD

**Issue by dnguyener** [nvim-telescope/telescope-project.nvim#13] opened 2021-03-08 19:16 UTC
First of all, great project!  Something I was looking for.  Is there a way to stay at the prompt after selecting a project?   I realize I can just hit "i" to go to the prompt but with file_browser that is not the case.  I would like to have it consistent.

**Comment by claidler** [comment] 2021-03-08 21:17
Thanks @dnguyener can you please explain the exact steps, as I'm not sure if I'm understanding correctly? I open the project list and whether I press, either 's' (to search in files) or 'f' (to search for files), I never have to hit 'i' to go the prompt.

**Comment by dnguyener** [comment] 2021-03-08 23:14
Claidler,

1) Open the project list.  You'll see a list of projects in the "Projects" window.  You can type whatever you want in the prompt.
2)  Select one of your projects project.  The project opens up and files are displayed in the "Results" window however you're no longer at the prompt.  I believe it's in normal mode after selecting a project?

**Comment by claidler** [comment] 2021-03-09 09:03
@dnguyener Ah you're right, if you press enter, rather than 's' or 'f', it does take you into normal mode. Yes, agreed, that's not consistent or very nice. I'll see if I can resolve this one. Thanks

**Comment by Conni2461** [comment] 2021-03-09 09:17
If i get this correctly than this is a bug in telescope. We haven't figured out why this happens but we have a workaround for this.
We would need to make this workaround public:
https://github.com/nvim-telescope/telescope.nvim/blob/1c80a92d4027c03b65cce1fe27ef664cff77186d/lua/telescope/actions/init.lua#L199-L217

Calling this function rather than close like that `  do_close(prompt_bufnr, true)` will keep insert mode

**Comment by elianiva** [comment] 2021-03-09 11:09
could also resolve this issue if we expose that function. https://github.com/nvim-telescope/telescope.nvim/issues/600

**Comment by claidler** [comment] 2021-03-10 20:08
Much appreciated @Conni2461 as always. I'll update this shortly

**Comment by Conni2461** [comment] 2021-03-10 20:23
I would accept a PR ;)

**Comment by claidler** [comment] 2021-03-10 20:48
I can't figure this out @Conni2461 I'm not currently running any close functions here.

https://github.com/nvim-telescope/telescope-project.nvim/blob/master/lua/telescope/_extensions/project.lua#L31-L59
Here, `actions.select_default:replace(on_project_selected)` is calling `project_actions.find_project_files`

Which calls this - 
https://github.com/nvim-telescope/telescope-project.nvim/blob/master/lua/telescope/_extensions/project_actions.lua#L66-L70

**Comment by Conni2461** [comment] 2021-03-10 20:55
Oh yeah you would need to call `actions._close(prompt_bufnr, true)` before running `builtin.find_files`. But `_close`/`do_close` is still local so you would need to make it part of `actions` first :) (I prefer the name `_close` more :laughing: ) 

Thats why i would accept a PR ;)

**Comment by claidler** [comment] 2021-03-10 21:13
Thanks @Conni2461 that would have been tough to figure out! I've set up a PR - https://github.com/nvim-telescope/telescope-project.nvim/pull/14

**Comment by Conni2461** [comment] 2021-03-10 21:18
Oh i meant i would accept a PR in telescope that makes the `do_close` function part of `actions`, so you don't have to re implement :laughing:

**Comment by claidler** [comment] 2021-04-10 20:10
Hi @dnguyener I believe this should be fixed with the latest update. Sorry it took a while. I'll close it, but let me know if you're still having issues. Thanks

**Closed by claidler** 2021-04-10 20:10 UTC

**Comment by danymat** [comment] 2022-01-12 19:04
Hello, it feels like the issue is still here, can you check again ? I experience it on latest version

**Comment by fdschmidt93** [comment] 2022-01-12 19:07
I'm not using `telescope-project` but if it follows "Open Project finder" and then "some other finder" it probably is more a telescope upstream problem related to prompt buffers 

https://github.com/nvim-telescope/telescope.nvim/pull/1600 hopefully fixes that eventually

**Comment by renerocksai** [comment] 2022-01-19 07:24
In my plugin, I was able to resolve nested picker issues by:

```lua
-- ...
actions._close(prompt_bufnr, false)
vim.schedule(function()
    call_follow_up_picker(...)
end)
```

**Comment by tiagovla** [comment] 2022-01-21 22:28
I can confirm that changing this line https://github.com/nvim-telescope/telescope-project.nvim/blob/ad33c9eb67de635ded67069af7552d5162497b1e/lua/telescope/_extensions/project/actions.lua#L104 to
```lua
if cd_successful then vim.schedule(function() builtin.find_files { cwd = project_path, hidden = hidden_files } end) end
```
fixes it.
